### ISSUE TITLE
Line Visualization Header Overlap

### ISSUE THREAD

**Issue by apothuku** [apothuku/aclu-cash-bail#15]
My only issue is this overlap which happens in my browser:
![Screen Shot 2020-10-24 at 8 49 53 PM](https://user-images.githubusercontent.com/4998601/97096478-76bf8f80-165c-11eb-9d0d-f17c8a94705b.png)

_Originally posted by @apothuku in https://github.com/aclu-cash-bail-team/aclu-cash-bail/pull/12#issuecomment-716075839_

**Comment by alexwgraves** [comment]
Yeah, discussed with Rong. We're going to try out moving the labels apart so that the right edge of the "White" label aligns with its line while the left edge of the "Black" label aligns with its line.

**Comment by apothuku** [comment]
Closed with #14
